# Generated by Django 4.0.5 on 2022-06-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegisterModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('user_email', models.EmailField(help_text='user_email', max_length=100)),
                ('user_password', models.CharField(help_text='user_password', max_length=50)),
                ('user_twitterhandle', models.CharField(help_text='user_twitter_username', max_length=100)),
                ('user_mobile', models.IntegerField(help_text='user_mobile')),
                ('user_location', models.CharField(help_text='user_location', max_length=50, null=True)),
                ('user_status', models.CharField(default='Pending', help_text='user_status', max_length=20)),
                ('user_reg', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'User_details',
            },
        ),
    ]
