# Generated by Django 4.0.5 on 2022-07-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_tagnamesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagnamesmodel',
            name='count',
            field=models.BigIntegerField(default=1, help_text='Number_of_searches'),
        ),
    ]
