# Generated by Django 4.0.5 on 2022-07-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_tagnamesmodel_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagnamesmodel',
            old_name='data',
            new_name='date',
        ),
    ]
